# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

[es]
  languageCode = "es"
  contentDir = "content/spa"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.


# Uncomment the lines below to configure your website in a second language.
### [en-us]
###   languageCode = "en-us"
###   contentDir = "content/en"
###   title = "Lab. de Biologia Computacional"
###   staticDir = "static"
###   weight = 1
###   languageName = "English"
###   [en-us.params]
###     description = "Lab. de Biologia Computacional"
###   [[en-us.menu.main]]
###   name = "Our Lab"
###   url = "#demo"
###   weight = 10
###   
###   [[en-us.menu.main]]
###   name = "History"
###   url = "#about"
###   weight = 11
### 
### 
###   
###   [[en-us.menu.main]]
###   name = "Research lines"
###   url = "#research_lines"
###   weight = 13
### 
###   [[en-us.menu.main]]
###   name = "Grants"
###   url = "#project"
###   weight = 20
### 
###   [[en-us.menu.main]]
###   name = "Members"
###   url = "#people"
###   weight = 21
### 
###   [[en-us.menu.main]]
###   name = "Selected publications"
###   url = "#publications"
###   weight = 30
### 
###   [[en-us.menu.main]]
###   name = "Publications"
###   url = "whole_publication/"
###   weight = 40
### 
###   [[en-us.menu.main]]
###   name = "Contact"
###   url = "#contact"
###   weight = 50
### 
###   [[en-us.menu.main]]
###   name = "Courses"
###   url = "courses/"
###   weight = 60
###   
### 
### [es]
###   languageCode = "es"
###   contentDir = "content/spa"
###   title = "Lab. de Biologia Computacional"
###   weight = 2
###   staticDir = "content/spa/static"
###   languageName = "Spa"
###   [es.params]
###     description = "Lab. de Biologia Computacional"
###   [[es.menu.main]]
###   name = "Nuestro Laboratorio"
###   url = "#demo"
###   weight = 10
###   
###   [[es.menu.main]]
###   name = "Historia"
###   url = "#about"
###   weight = 11
### 
###   [[es.menu.main]]
###   name = "Líneas de trabajo"
###   url = "#research_lines"
###   weight = 13
### 
###   [[es.menu.main]]
###   name = "Proyectos"
###   url = "#project"
###   weight = 20
### 
###   [[es.menu.main]]
###   name = "Miembros"
###   url = "#people"
###   weight = 21
### 
###   [[es.menu.main]]
###   name = "Publicaciones destacadas"
###   url = "#publications"
###   weight = 30
### 
###   [[es.menu.main]]
###   name = "Publicaciones"
###   url = "whole_publication/"
###   weight = 40
### 
###   [[es.menu.main]]
###   name = "Contacto"
###   url = "#contact"
###   weight = 50
### 
###   [[es.menu.main]]
###   name = "Cursos"
###   url = "courses/"
###   weight = 60### 